[alembic]
script_location = src/bot/sessions/migrations
prepend_sys_path = .
sqlalchemy.url = sqlite:///./.data/chats.db

[rag]
script_location = src/bot/rag/migrations
prepend_sys_path = .
sqlalchemy.url = sqlite:///./.data/rag.db
