"""rag documents, chunks and vec0 vectors

Revision ID: 0001
Revises:
Create Date: 2026-09-09 15:11:34.075641

"""

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None

# Размерность вектора bge-m3 на момент создания ревизии. Миграция —
# застывший снимок: намеренно без импорта из bot.rag.models, чтобы
# смена константы не переписывала DDL уже применённых схем.
_EMBEDDING_DIMENSION = 1024


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(
            "chunks_document_id_position", ["document_id", "position"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("documents_owner_id_name", ["owner_id", "name"], unique=True)

    # Виртуальная таблица векторов vec0 невыразима в метаданных SQLAlchemy,
    # поэтому добавляется в ревизию вручную (единственное исключение из
    # автогенерации, см. bot/rag/migrations/__init__.py): чанк ссылается
    # на вектор, косинусная метрика даёт distance = 1 − косинусная близость.
    op.execute(
        "CREATE VIRTUAL TABLE chunk_vectors USING vec0("
        "chunk_id INTEGER PRIMARY KEY, "
        f"embedding FLOAT[{_EMBEDDING_DIMENSION}] distance_metric=cosine)"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS chunk_vectors")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("documents_owner_id_name")

    op.drop_table("documents")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("chunks_document_id_position")

    op.drop_table("chunks")
    # ### end Alembic commands ###
